version: 2
jobs:
  update_and_commit_all:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            sudo pip install -r requirements.txt
            . update_and_commit_all.sh
workflows:
  version: 2
  build:
    jobs:
      - update_and_commit_all
  nightly:
    triggers:
      - schedule:
          cron: "0 0 12 * * ?"
          filters:
            branches:
              only:
                - master
    jobs:
      - update_and_commit_all
